name: 🚀 Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no root@liveinsync.in << 'EOF'
          # Navigate to your application directory
          cd /dwellsync-android

          # Pull the latest code
          git pull --rebase origin main

          # Install Node.js dependencies
          npm install

          # Build the TypeScript backend
          npm run build

          # Install PM2 globally if not already installed
          npm install -g pm2

          # Start or restart the application with PM2
          # Using --name to give it a memorable process name in PM2
          pm2 startOrRestart dist/index.js --name dwellsync-backend

          # Save PM2 process list across reboots (optional, but recommended)
          pm2 save
        EOF
